parameters:
  - name: ref
    type: string
    default: main

trigger: none

variables:
  - group: docker
  - group: dockerhub
  - group: acr

resources:
  repositories:
    - repository: templates
      type: git
      endpoint: docker/templates
      ref: ${{ parameters.ref }}

extends:
  template: build.yml@templates
  parameters:
    agentPool:
      vmImage: ubuntu-latest
    serviceConnection: azure