trigger: none

stages:
  - stage: build
    displayName: ACR Build and Push
    jobs:
      - job: acr_docker_build
        displayName: Docker Build and Push
        workspace:
          clean: all
        steps:
          - checkout: self
          - task:  Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: ACR
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: leriksen/hreporter
              tags: |
                $(Build.BuildId)
                latest
      - job: dockerhub_docker_build
        displayName: DockerHub Build and Push
        workspace:
          clean: all
        steps:
          - checkout: self
          - task:  Docker@2
            displayName: Login to Dockerhub
            inputs:
              command: login
              containerRegistry: DockerHub
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: leriksen/hreporter
              tags: |
                $(Build.BuildId)
                latest
